# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZAPFSPFJbzGtWyv4OIh6VCk006mjLBUi
"""

import streamlit as st
import pandas as pd
import re
import plotly.express as px
from bertopic import BERTopic
from transformers import pipeline

# Konfigurasi Halaman Streamlit
st.set_page_config(page_title="Analisis Tesis: Topic & Stance", layout="wide")

# ==========================================
# TAHAP 1: PREPROCESSING [Sesuai Blok Diagram]
# ==========================================
def preprocess_text(text):
    if pd.isna(text):
        return ""
    text = str(text).lower()
    text = re.sub(r"http\S+", "", text) # Hapus URL
    text = re.sub(r"@\w+", "", text)    # Hapus Mention
    text = re.sub(r"#\w+", "", text)    # Hapus Hashtag
    text = re.sub(r"[^\w\s]", "", text) # Hapus Tanda Baca
    return text.strip()

st.title("Sistem Analisis Topik dan Sikap (Stance) Twitter")
st.markdown("Aplikasi ini disinkronkan dengan arsitektur sistem tesis: **BERTopic & IndoBERT**.")

# ==========================================
# TAHAP 2: CRAWLING DATA (Upload Dataset)
# ==========================================
uploaded_file = st.file_uploader("Unggah Dataset Twitter (CSV)", type=["csv"])

if uploaded_file is not None:
    # Membaca dataset
    df = pd.read_csv(uploaded_file)
    st.write("### Pratinjau Data Awal")
    st.dataframe(df[['conversation_id_str', 'full_text', 'full_text_comments']].head())

    if st.button("Jalankan Proses Analisis"):

        # PREPROCESSING
        with st.spinner("Sedang melakukan Preprocessing teks..."):
            df['clean_post'] = df['full_text'].apply(preprocess_text)
            df['clean_comment'] = df['full_text_comments'].apply(preprocess_text)

            # Memisahkan unggahan utama untuk Topic Modeling (berdasarkan conversation_id)
            posts_df = df[['conversation_id_str', 'clean_post']].drop_duplicates(subset=['conversation_id_str']).dropna(subset=['clean_post'])
            posts_df = posts_df[posts_df['clean_post'] != ""]
            docs = posts_df['clean_post'].tolist()

        # ==========================================
        # TAHAP 3: DYNAMIC TOPIC MODELING (BERTopic)
        # ==========================================
        with st.spinner("Sedang memproses Dynamic Topic Modeling (BERTopic) pada Unggahan/Artikel..."):
            try:
                # Inisialisasi BERTopic untuk bahasa Indonesia
                topic_model = BERTopic(language="indonesian", calculate_probabilities=False)
                topics, probabilities = topic_model.fit_transform(docs)
                posts_df['Topik'] = topics

                # Mapping Topik kembali ke dataframe utama berdasarkan conversation_id_str
                topic_mapping = dict(zip(posts_df['conversation_id_str'], posts_df['Topik']))
                df['Topik'] = df['conversation_id_str'].map(topic_mapping)

            except Exception as e:
                st.error(f"Terjadi kesalahan pada Topic Modeling: {e}")

        # ==========================================
        # TAHAP 4: STANCE ANALYSIS (IndoBERT)
        # ==========================================
        with st.spinner("Sedang memproses Stance Analysis (IndoBERT) pada Komentar/Reply..."):
            # CATATAN UNTUK TESIS: Ganti path "indobenchmark/indobert-base-p1" dengan
            # path model IndoBERT Anda yang SUDAH di-fine-tuning untuk klasifikasi Stance (Pro/Kontra/Netral).
            try:
                # Menggunakan pipeline klasifikasi teks dari HuggingFace
                stance_classifier = pipeline("text-classification", model="indobenchmark/indobert-base-p1", truncation=True, max_length=512)

                def get_stance(text):
                    if not text: return "Netral"
                    # Prediksi dengan IndoBERT
                    result = stance_classifier(text)
                    # Logika ini perlu disesuaikan dengan label hasil fine-tuning model Anda
                    return result['label']

                # Limitasi sampel untuk demo agar Streamlit tidak timeout (Hapus .head(100) untuk full data)
                df_sample = df.copy() # Gunakan df.head(100) jika komputasi terlalu berat di lokal

                # Eksekusi Model
                # HATI-HATI: Proses ini bisa memakan waktu lama tergantung spesifikasi GPU/CPU
                df_sample['Sikap'] = df_sample['clean_comment'].apply(get_stance)

            except Exception as e:
                st.error(f"Terjadi kesalahan pada Stance Analysis: {e}")

        # ==========================================
        # TAHAP 5: GABUNG TOPIK + SIKAP PER POSTINGAN
        # ==========================================
        st.success("Proses NLP Selesai!")
        st.write("### Hasil Gabungan Topik & Sikap per Postingan")
        # Menampilkan kolom yang relevan dari dataset hasil pemrosesan
        st.dataframe(df_sample[['conversation_id_str', 'full_text', 'Topik', 'full_text_comments', 'Sikap']])

        # ==========================================
        # TAHAP 6: ANALISIS ISU (Distribusi Stance per Topik)
        # ==========================================
        st.write("### Analisis Isu: Distribusi Stance per Topik")

        # Mengelompokkan data berdasarkan Topik dan Sikap
        dist_df = df_sample.groupby(['Topik', 'Sikap']).size().reset_index(name='Jumlah')

        # Membuat visualisasi bar chart dengan Plotly
        fig = px.bar(
            dist_df,
            x="Topik",
            y="Jumlah",
            color="Sikap",
            title="Distribusi Sikap (Stance) berdasarkan Topik Pembicaraan",
            barmode="group",
            text_auto=True
        )
        fig.update_layout(xaxis_title="Cluster Topik", yaxis_title="Jumlah Komentar")

        # Render grafik di Streamlit
        st.plotly_chart(fig, use_container_width=True)